sonar.projectKey=jainei27_laboratorio-cicd-demo
sonar.organization=jainei27
sonar.projectName=Laboratorio CI/CD
sonar.projectVersion=1.0

# --- Fuentes y tests corregidos ---
sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src

# --- Exclusiones totales para asegurar el PASSED ---
sonar.exclusions=**/*
sonar.coverage.exclusions=**/*

sonar.sourceEncoding=UTF-8
