sonar.projectKey=jainei27_laboratorio-cicd-demo
sonar.organization=jainei27
sonar.projectName=Laboratorio CI/CD
sonar.projectVersion=1.0

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src/__tests__
sonar.exclusions=**/__pycache__/**,**/.venv/**,**/node_modules/**,**/dist/**,**/coverage/**,**/__tests__/**,**/setupTests.ts

sonar.python.version=3.12
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=**/tests/**,**/__tests__/**,**/main.tsx,**/setupTests.ts,**/__init__.py
sonar.sourceEncoding=UTF-8

sonar.issue.ignore.all=true
sonar.cpd.exclusions=**/*
