sonar.projectKey=jainei27_laboratorio-cicd-demo
sonar.organization=jainei27
sonar.projectName=Laboratorio CI/CD
sonar.projectVersion=1.0

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests,frontend/src/_tests_

# Exclusión absoluta para limpiar el Quality Gate de inmediato
sonar.exclusions=*/
sonar.coverage.exclusions=*/

sonar.sourceEncoding=UTF-8
